### ISSUE TITLE
Login error, multiple errors

### ISSUE THREAD

**Issue by networxnet** [marzzzello/pytr#17]
When login:

20:58:24 Credentials not saved
Traceback (most recent call last):
  File "C:\Users\psc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytr\api.py", line 188, in inititate_weblogin
    self._process_id = j['processId']
KeyError: 'processId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\psc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\pytr.exe\__main__.py", line 7, in <module>
  File "C:\Users\psc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytr\main.py", line 121, in main
    login(phone_no=args.phone_no, pin=args.pin, web=weblogin)
  File "C:\Users\psc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytr\account.py", line 70, in login
    countdown = tr.inititate_weblogin()
  File "C:\Users\psc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytr\api.py", line 192, in inititate_weblogin
    raise ValueError(str(err))
ValueError: [{'errorCode': 'NUMBER_INVALID', 'errorMessage': 'phoneNumber', 'meta': None}]

Windows 10, see simliar errors in reddit posts for example

**Comment by C0D3D3V** [comment]
This is a error, that trade republic send you directly. You have only to read the last line. 
```
ValueError: [{'errorCode': 'NUMBER_INVALID', 'errorMessage': 'phoneNumber', 'meta': None}]
```

Your phone number is incorrect. Make sure you set a correct phone number.

**Comment by marzzzello** [comment]
Also use the issue template next time

**Comment by networxnet** [comment]
> Thank you! "Sometimes you can't see the forest for the trees." ;) Missed the country prefix, because App asks for it without  prefix.

> Also use the issue template next time

Ok, sorry.

**Comment by marzzzello** [comment]
:smile_cat: no problem, btw I just released a new version. If you have any problems with file paths or file not found then it it should be fixed now in 0.0.15
