### ISSUE TITLE
Download can't handle spaces in path

### ISSUE THREAD

**Issue by networxnet** [marzzzello/pytr#18]
**Description of the bug**
The download path will not be accepted if it contains a directory with spaces, e.g. "Trade Republic".

**To Reproduce**
1. Ran the command "pytr dl_docs C:\Daten\Trade Republic"
2. See output "usage: pytr [-h] [-s {bash,zsh,tcsh}] [-v {warning,info,debug}] [--applogin] [-V]
            {help,login,portfolio,dl_docs,get_price_alarms,details,set_price_alarms} ...
pytr: error: unrecognized arguments: Republic"
3. No download is performed

**Expected behavior**
Download of docs to the given/existing path

**Error log**
pytr: error: unrecognized arguments: Republic

**Environment**
 - OS: Windows
 - Version: 10 20H2
 - Python 3.9

**Comment by marzzzello** [comment]
Try to set the file path in quotes. Or add a backslash before the space

**Comment by marzzzello** [comment]
@networxnet thanks very much for sponoring!

**Comment by networxnet** [comment]
Path in quotes. 
Windows uses ^ oder ` instead of \ but this is not working in batch when using &&.

**Comment by marzzzello** [comment]
Ah, good to know

**Comment by networxnet** [comment]
To explain the issue more clearly. This is the full batch call to start download:

`cmd /k "C:\Trade Republic\Script\pytr login && C:\Trade Republic\Script\pytr dl_docs C:\Trade Republic"`

Any idea how to handle the spaces?

**Comment by marzzzello** [comment]
You don't need to separately login before. The login command is just to test the login and exit. 
The other commands make sure you are logged in before proceeding.
 
Try this:
```
cmd /k "C:\Trade Republic\Script\pytr dl_docs 'C:\Trade Republic'"
```

**Comment by networxnet** [comment]
So login will performed with pytr dl_docs ...?
 
 cmd /k "C:\Trade Republic\Script\pytr dl_docs 'C:\Trade Republic'"  will not work.

**Comment by marzzzello** [comment]
> So login will performed with pytr dl_docs ...?

Yes. Same as `pytr login`
 
> cmd /k "C:\Trade Republic\Script\pytr dl_docs 'C:\Trade Republic'" will not work.

What's the error?

**Comment by networxnet** [comment]
Der Befehl "C:\Trade" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

**Comment by marzzzello** [comment]
What about you just change the directory name to `C:\TradeRepulic` without space?
And where are you entering the command? Normally you just open the terminal and type the command without `cmd /k`.

**Comment by C0D3D3V** [comment]
You could use `^` to escape spaces like this:
```
cmd /k "C:\Trade^ Republic\Script\pytr dl_docs C:\Trade^ Republic"
```
But as @marzzzello  already said, you do not have to run the command with `cmd /k`. Also if you installed pytr using `pip` (Just install python and run `pip install pytr`). 
Than you should be able to run pytr like this: `pytr dl_docs C:\Trade^ Republic`

**Comment by networxnet** [comment]
;) Not so easy as there are other tools accessing.

As explaint further up this was a batch file to perform login and download afterwards ... and maybe for scheduling.
 /k is for not closing the cmd window, so i can see the messages from pytr after command/job is finished.
 
 When login command is not needed, i can use " ..."

**Comment by networxnet** [comment]
Other question ... next abovehow long will the session last? When is new code needed?

**Comment by marzzzello** [comment]
> Other question ... next abovehow long will the session last? When is new code needed?

I think the session is 5 minutes. If you do a request in less than 5 minutes no new code is needed and the session extends for another 5 minutes

**Comment by networxnet** [comment]
Must be more then 5 minutes.

**Comment by marzzzello** [comment]
> ;) Not so easy as there are other tools accessing.
> 
> As explaint further up this was a batch file to perform login and download afterwards ... and maybe for scheduling. /k is for not closing the cmd window, so i can see the messages from pytr after command/job is finished.
> 
> When login command is not needed, i can use " ..."

Have you tried running it without a batch file? Is it working fine then?
Another idea to replace single quotes with double quotes and vice versa:
```
cmd /k 'C:\Trade Republic\Script\pytr dl_docs "C:\Trade Republic"''
```
Or use ^ before space

**Comment by marzzzello** [comment]
> Seems to be far more then 5 minutes.

I just tested and it's less than 6.5 minutes. 
Have you tested with dl_docs? As long as it's running the session is automatically extended.

**Comment by networxnet** [comment]
> > Seems to be far more then 5 minutes.
> 
> ~I just tested and it's less than 6.5 minutes.~ Nevermind, it asks me everytime idk why Have you tested with dl_docs? As long as it's running the session is automatically extended.

Seems to be more tricky ... first i have to enter no new code for hours, and now no code sms is send anymore :( I also got no code in app.
Webapp tells me "Du hast deine Pin zu oft falsch eingegeben"

**Comment by marzzzello** [comment]
If you request a new code without entering the previous one correctly the countdown extends and you can't request new codes in this timeframe

**Comment by networxnet** [comment]
Code not PIN. I got codes by sms, when login with webapp, but not with pytr.

I have already deleted credentials and cockies file, without luck.
Is it possible TR locks the device ID?

**Comment by marzzzello** [comment]
code yes. You can request a SMS too. There was a bug, it should be fixed in 0.0.16.
The countdown makes sure the SMS is not requested too early. Normally it is 30 seconds. 
>  Is it possible TR locks the device ID?

pytr uses the same the same login method as the webinterface. You just need to wait for the countdown to reach zero. Then you can retry

**Comment by networxnet** [comment]
> > > Seems to be far more then 5 minutes.
> > 
> > 
> > ~I just tested and it's less than 6.5 minutes.~ Nevermind, it asks me everytime idk why Have you tested with dl_docs? As long as it's running the session is automatically extended.
> 
> Seems to be more tricky ... first i have to enter no new code for hours, and now no code sms is send anymore :( I also got no code in app. Webapp tells me "Du hast deine Pin zu oft falsch eingegeben"

For me generally only sms code is workng. 

But good hint!

 Countdown don't run. 
"Enter nothing if you want to receive the code as SMS instead. (Countdown: 121)"

And then the seconds will not decrease. Its since i update to 0.0.15 ...

**Comment by networxnet** [comment]
![image](https://user-images.githubusercontent.com/16120065/147976667-fd916b84-494f-4ddb-956f-017cc17b7171.png)

**Comment by marzzzello** [comment]
I just fixed SMS requesting in 0.0.16. If it's still not working then it's a windows specific problem. You could try to use WSL2 then
Looks like your Windows environment is a bit broken anyway.
I recommend to use WSL2 (Windows Subsystem for Linux)

**Comment by networxnet** [comment]
Account was blockt and corrupt on TRs side. They did a reset today. Additionally i have fixed the code issue in app.
So login is fully working again.

But new problems and i'm not sure if this is also a problem with handle spaces.

22:19:04 Awaiting #1  timeline
22:19:04 Connecting to websocket ...
22:19:04 Connected to websocket ...
22:19:04 Received #1  timeline, awaiting #2  timeline
22:19:04 Received #2  timeline, awaiting #3  timeline
22:19:04 Received #3  timeline, awaiting #4  timeline
22:19:05 Received #4  timeline, awaiting #5  timeline
22:19:05 Received #5  timeline, awaiting #6  timeline
22:19:05 Received #6  timeline, awaiting #7  timeline
22:19:05 Received #7  (last) timeline
22:19:05   1/175: Basisinformationen -- Mi. 08.05. um 22:14 Uhr (Europe/Berlin)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "M:\Finanzen\Trade Republic\Script\pytr.exe\__main__.py", line 7, in <module>
  File "C:\Users\psc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytr\main.py", line 130, in main
    asyncio.get_event_loop().run_until_complete(dl.dl_loop())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\psc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytr\dl.py", line 49, in dl_loop
    await self.tl.timelineDetail(response, self, max_age_timestamp=self.since_timestamp)
  File "C:\Users\psc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytr\utils.py", line 237, in timelineDetail
    dl.dl_doc(doc, response['titleText'], response['subtitleText'])
  File "C:\Users\psc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytr\dl.py", line 98, in dl_doc
    filepath = sanitize_filepath(filepath, '_', os_name)
  File "C:\Users\psc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pathvalidate\_filepath.py", line 442, in sanitize_filepath
    return FilePathSanitizer(
  File "C:\Users\psc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pathvalidate\_filepath.py", line 84, in sanitize
    self.__fpath_validator.validate_abspath(value)
  File "C:\Users\psc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pathvalidate\_filepath.py", line 255, in validate_abspath
    raise err_object
pathvalidate.error.ValidationError: **reason=MALFORMED_ABS_PATH, target-platform=universal, description=an invalid absolute file path (M:\Finanzen\Trade Republic\Basisinformationen über Wertpapiere\2019-05-08 2214 Basisinformationen.pdf)** for the platform (universal). to avoid the error, specify an appropriate platform correspond with the path format, or 'auto'.

**Comment by marzzzello** [comment]
Should be fixed in latest version

**Comment by marzzzello** [comment]
How was the account blocked by TR?

**Comment by networxnet** [comment]
> Should be fixed in latest version

I will test this evening

**Comment by networxnet** [comment]
> How was the account blocked by TR?

🤷🏻‍♂️ they not told me in detail. Too many unsuccessful login attempts so timer is set to unlimited as I understand.

**Comment by networxnet** [comment]
> Should be fixed in latest version

Now it seems to work. Thank you for your patient and quick support.

**Comment by marzzzello** [comment]
> > How was the account blocked by TR?
> 
> 🤷🏻‍♂️ they not told me in detail. Too many unsuccessful login attempts so timer is set to unlimited as I understand.

Yeah, that's just the automatic rate limiting. For every time you request a code and don't use it the countdown doubles until you can request a new code (starting with 30 seconds)


> Now it seems to work. Thank you for your patient and quick support.

Nice. Thanks for reporting the issues.
