### ISSUE TITLE
Problems with dl_docs, installing problem?

### ISSUE THREAD

**Issue by nPyRoX** [marzzzello/pytr#4]
Hi all,

I think I am doing something fundamental wrong. Maybe anyone can help. Just installed via pip the new version. logged successfully in and tried to dl_docs path

Command used: 
pytr dl_docs PATH

```
Awaiting #1  timeline
Received #1  timeline, awaiting #2  timeline
Received #2  timeline, awaiting #3  timeline
Received #3  timeline, awaiting #4  timeline
Received #4  timeline, awaiting #5  timeline
Received #5  timeline, awaiting #6  timeline
Received #6  timeline, awaiting #7  timeline
Received #7  (last) timeline
1/209:   -- Fr. 18.12. um 12:19 Uhr (Europe/Berlin) -- istSparplan: False
2/209: Steuerabrechnung -- Sa. 19.12. um 01:04 Uhr (Europe/Berlin) -- istSparplan: False
3/209: Kauf Taat Lifestyle+Wellness -- Fr. 18.12. um 08:19 Uhr (Europe/Berlin) -- istSparplan: False
4/209: Verkauf Long @71.77 € Zalando Open End Turbo -- Fr. 18.12. um 19:23 Uhr (Europe/Berlin) -- istSparplan: False
5/209: Verkauf Long @71.80 € Zalando Open End Turbo -- Mo. 21.12. um 08:14 Uhr (Europe/Berlin) -- istSparplan: False
6/209:   -- Do. 05.11. um 10:32 Uhr (Europe/Berlin) -- istSparplan: False
7/209: Basisinformationen -- Do. 05.11. um 10:32 Uhr (Europe/Berlin) -- istSparplan: False
8/209:   -- Do. 05.11. um 10:32 Uhr (Europe/Berlin) -- istSparplan: False
9/209: Basisinformationen -- Do. 05.11. um 10:32 Uhr (Europe/Berlin) -- istSparplan: False
file path/Basisinformationen über Wertpapiere/2020-11-05 10:32 Basisinformationen -  Do. 05.11. um 10:32 Uhr (Europe/Berlin).pdf already in queue. Skipping...
Received error message: '17 E {"errors":[{"errorCode":"BAD_REQUEST","errorField":null,"errorMessage":"Bad Request","meta":{"source":"PLATFORM"}}]}'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/pytr", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytr/main.py", line 135, in main
    asyncio.get_event_loop().run_until_complete(dl.dl_loop())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytr/dl.py", line 28, in dl_loop
    _subscription_id, subscription, response = await self.tr.recv()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytr/api.py", line 246, in recv
    raise TradeRepublicError(subscription_id, subscription, payload)
pytr.api.TradeRepublicError: ('17', {'type': 'timelineDetail', 'id': 'a685439a-606f-4070-980c-830278ade8b5'}, {'errors': [{'errorCode': 'BAD_REQUEST', 'errorField': None, 'errorMessage': 'Bad Request', 'meta': {'source': 'PLATFORM'}}]})

```

**Comment by marzzzello** [comment]
See #3 
Upgrade with `pip install --upgrade pytr`
