### ISSUE TITLE
Connection Error on dl_docs

### ISSUE THREAD

**Issue by tomraley** [marzzzello/pytr#49]
Hi, when trying to download documents I get connection error. Worked fine in the past...

**Error log**

```
pytr dl_docs .      
23:19:02 Found credentials file
23:19:02 Phone: +49160********, PIN: ****
23:19:03 Web session resumed
23:19:03 Logged in
23:19:03 Awaiting #1  timeline
23:19:03 Connecting to websocket ...
Traceback (most recent call last):
  File "/usr/local/bin/pytr", line 10, in <module>
    sys.exit(main())
  File "/Library/Python/3.7/site-packages/pytr/main.py", line 152, in main
    asyncio.get_event_loop().run_until_complete(dl.dl_loop())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Library/Python/3.7/site-packages/pytr/dl.py", line 34, in dl_loop
    await self.tl.get_next_timeline(max_age_timestamp=self.since_timestamp)
  File "/Library/Python/3.7/site-packages/pytr/utils.py", line 100, in get_next_timeline
    await self.tr.timeline()
  File "/Library/Python/3.7/site-packages/pytr/api.py", line 438, in timeline
    return await self.subscribe({'type': 'timeline', 'after': after})
  File "/Library/Python/3.7/site-packages/pytr/api.py", line 288, in subscribe
    ws = await self._get_ws()
  File "/Library/Python/3.7/site-packages/pytr/api.py", line 274, in _get_ws
    raise ValueError(f'Connection Error: {response}')
ValueError: Connection Error: failed 31
```

**Environment**

- OS: Mac OS 14.2.1 (23C71)
- pytr version: (pytr: error: unrecognized arguments: -V)

**Comment by tomraley** [comment]
Solution: Update way outdated pytr (0.0.X) to newer version (0.1.9). Works again.
