### ISSUE TITLE
ssl.SSLCertVerificationError

### ISSUE THREAD

**Issue by jvgh1** [marzzzello/pytr#6]
Hi - also thanks in advance. Unbelievable that it is so hard for them to make that data accessible. 

I ran into the following problem. Seems like there's no validation of SSL keys happening in Python? 
Not sure what to do -- and happy to learn how to navigate this issue. 

```19:19:37 Logged in
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/pytr", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytr/main.py", line 152, in main
    Portfolio(login()).get()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytr/portfolio.py", line 73, in get
    asyncio.get_event_loop().run_until_complete(self.portfolio_loop())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytr/portfolio.py", line 11, in portfolio_loop
    await self.tr.portfolio()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytr/api.py", line 279, in portfolio
    return await self.subscribe({'type': 'portfolio'})
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytr/api.py", line 188, in subscribe
    ws = await self._get_ws()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytr/api.py", line 168, in _get_ws
    self._ws = await websockets.connect('wss://api.traderepublic.com')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/websockets/legacy/client.py", line 622, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/sslproto.py", line 528, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)```

**Comment by marzzzello** [comment]
That is a Python+Windows problem
How did you install Python?

**Comment by jvgh1** [comment]
Thanks, it worked! 

I used Python on Mac and I installed it via Terminal: 

`git clone https://github.com/marzzzello/pytr.git
cd pytr
pip3 install .`
